### ISSUE TITLE
std::setfill is used by istream.

### ISSUE THREAD

**Issue by virtualmatador** [virtualmatador/cron#1]
When parsing field, std::setfill is called on istream object but this function is meant to be used by std::ostream objects.
The goal was to make istream to stop at `-` character when parsing the number but it's not needed since istream will stop at `-` anyway.

**Comment by Combuster54** [comment]
Yes. The solution is to remove the call to std::setfill on the istream object. The istream will stop at the - character anyway, so this call is unnecessary.
